ProjectUtsB02/urls.py
from django.contrib import admin
from django.urls import include, path
from django import urls
from django.urls.conf import include
import saran.urls as saran
import daftar.urls as daftar
import feedback.urls as feedback
import user_profile.urls as profile
from login.views import logoutUser
from daftar.views import registFlutter, index
import login.urls as login_url
import dana.urls as dana
import pengutaraan.urls as pengutaraan
import profil.urls as profil
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('saran/', include(saran)),
    path('login/', include(login_url)),
    path('feedback/', include(feedback)),
    path('daftar/', index, name="daftar"),
    path('profile/', include(profile)),
    path('logout/', logoutUser, name='logoutUser'),
    path('dana/', include(dana)),
    path('pengajuan/', include(pengutaraan)),
    path('profil/', include(profil)),
    path('daftar/flutterregist', registFlutter, name="flutter-regist"),
]

dana/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 
from .views import listDonasi, detailDonasi

app_name = 'dana'

urlpatterns = [
    path('formulir_donasi/', views.formulir, name='formulir_donasi'),
    path('donasi_berhasil/', views.berhasil, name='donasi_berhasil'),
    path('json/', listDonasi.as_view()),
    path('<int:pk>/', detailDonasi.as_view())
]

profil/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from .views import listProfil, detailProfil

urlpatterns = [
    path('create_profil/', views.create_profil, name = 'create_profil'),
    path('edit_profil/<str:pk>/', views.edit_profil, name='edit_profil'),
    path('', views.profil_view, name='profil_pengguna'),
    path('json', views.json, name="json"),
    path('jsonprofil/', listProfil.as_view()),
    path('<int:pk>/', detailProfil.as_view())

]

profil/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profil(models.Model):
    gender_choices = [
        (("Laki-laki", "Laki-laki")),
        (("Perempuan", "Perempuan")),
    ]

    role_choices = [
        (("Admin", "Admin")),
        (("Pengaju", "Pengaju")),
        (("Donatur", "Donatur")),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=300, null=True)
    email = models.EmailField(max_length=300, null=True)
    role = models.CharField(choices=role_choices, null=True, blank=True, max_length=300)
    gender = models.CharField(choices=gender_choices, null=True, blank=True, max_length=300)
    phone = models.CharField(max_length=300, null=True)
    birthday = models.DateField(default='2002-01-31')
    address = models.CharField(max_length=300, null=True)


    def __str__(self):
        return self.name
    

profil/forms.py
from django import forms
from django.db.models import fields
from .models import Profil

class ProfilForm(forms.ModelForm):
    class Meta:
        model = Profil
        fields = '__all__'
        exclude = ['user']

profil/views.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.query import QuerySet
from django.http import response
from django.shortcuts import redirect, render, get_object_or_404
from .models import Profil
from .forms import ProfilForm
from django.urls import reverse
from login.decorators import allowed_users
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse
from django.core import serializers
from .serializers import ProfilSerializers
from rest_framework import generics
# Create your views here.
class listProfil(generics.ListCreateAPIView):
    queryset = Profil.objects.all()
    serializer_class = ProfilSerializers

class detailProfil(generics.RetrieveUpdateAPIView):
    queryset = Profil.objects.all()
    serializer_class = ProfilSerializers

@login_required(login_url='login')
def create_profil(request):
    form = ProfilForm()
    if request.method == 'POST':
        form = ProfilForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/profil')
            
    context = {'form' : form}
    return render(request, 'form_profil.html', context)

@login_required(login_url='login')
def edit_profil(request, pk):
    #profil = Profil.objects.filter(user__username=request.user).first()
    key = Profil.objects.get(id=pk)
    #key = get_object_or_404(User, id=pk)
    form = ProfilForm(instance=key)
    
    if request.method == 'POST':
        form = ProfilForm(request.POST, instance=key)
        if form.is_valid():
            form.save()
            return redirect('/profil')
            
    context = {'form' : form}
    return render(request, 'form_profil.html', context)
    

@login_required(login_url='login')
#@allowed_users(allowed_roles=['admin'])
def profil_view(request):
    #profil = Profil.objects.filter(user__username=request.user)
    profil = Profil.objects.filter(user__username=request.user)
    context = {'profil':profil}
    return render(request, 'profil.html', context)

def json(request):
    data = serializers.serialize('json', Profil.objects.all())
    return HttpResponse(data, content_type = "application/json")

profil/templates/edit_form.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    
    
</head>  
<body>  
<form method="POST" class="post-form" action="../edit_profil/">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Nama:</label>  
    <div class="col-sm-4">  
        <input type="text" name="name" id="id_name" required maxlength="20" value="{{ profil.name }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Email:</label>  
    <div class="col-sm-4">  
        <input type="text" name="email" id="id_email" required maxlength="100" value="{{ profil.email }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Role:</label>  
    <div class="col-sm-4">  
        <input type="" name="role" id="id_role" required maxlength="254" value="{{ profil.role }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Gender:</label>  
    <div class="col-sm-4">  
        <input type="" name="gender" id="id_gender" required maxlength="15" value="{{ profil.gender }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">No.Telp:</label>  
    <div class="col-sm-4">  
        <input type="text" name="phone" id="id_phone" required maxlength="20" value="{{ profil.phone }}"/>  
    </div>  
  </div> 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">TTL:</label>  
    <div class="col-sm-4">  
        <input type="text" name="birthday" id="id_birthday" required maxlength="20" value="{{ profil.birthday }}"/>  
    </div>  
  </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Alamat:</label>  
    <div class="col-sm-4">  
        <input type="text" name="address" id="id_address" required maxlength="20" value="{{ profil.address }}"/>  
    </div>  
  </div>     
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>
<a href="../profil"><span class="glyphicon glyphicon-pencil" >Back</span>  
</body>  
</html>


 

profil/templates/form_profil.html
<div class="cont">
  <h5 style="color: white; text-align: center;">Data Pengaju</h5>
  <hr style="color: white; height: 2px">
  <form action="" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-sm btn-light btn-outline-warning" type="submit" name="Submit">
  </form>
</div>

profil/templates/profil.html
<div class="main">
     
    <!-- Specify fields to be displayed -->
    <a href="{% url 'create_profil' %}" class="btn btn-primary">Add New Record</a>
    {% for profil in profil %}
    Nama:{{ profil.name }}<br/>
    Email:{{ profil.email }}<br/>
    Role:{{ profil.role }}<br/>
    Gender:{{ profil.gender }}<br/>
    No.Telp:{{ profil.phone }}<br/>
    TTL:{{ profil.birthday }}<br/>
    Alamat:{{ profil.address }}<br/>
    <a class="btn btn-sm btn-light btn-outline-warning" href="{% url 'edit_profil' profil.pk %}">Update</a>
        
    {% endfor %}
</div>